# -*- mode: yaml -*-
owner: kmontag
repo: goat-upptime

assignees:
  # 
  - kmontag
  # 
  - redgoat650
  # 
  - yfnstn
  # 

sites:
  # 
  - name: "🐐"
    url: "$SITE_568638ca69cbb20df0a654a8007dd334a94d391dca44259b99833214527490fc"
  # 

status-website:
  # Adjust the base URL for serving on a standard GH pages URL.
  baseUrl: /goat-upptime
  name: "Goat Upptime"

# Don't manage repository metadata.
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
